server:
  port: 7700


spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

feign:
#  circuitbreaker:
#    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
        errorDecoder: edu.api.infrastructure.config.FeignClientErrorDecoder
        retryer: edu.api.infrastructure.config.FeignClientRetryer
        loggerLevel: BASIC


# Actuator
#management.endpoints.web.exposure.include: *
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true


# Circuit Breaker
#resilience4j:
#  ratelimiter:
#    instances:
#      CircuitBreakerPersonService:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 1s
#  circuitbreaker:
#    instances:
#      CircuitBreakerPersonService:
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 3
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        sliding-window-typ: count_based